spin_manifest_version = "1"
authors = ["Tobias Simetsreiter <dasimet@gmail.com>"]
description = ""
name = "spinapp"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "html"
source = "zig-out/bin/html.wasm"
[component.trigger]
route = "/..."
executor = { type = "wagi" }
[component.build]
command = "zig build html"


[[component]]
id = "key-value"
source = "zig-out/bin/key-value.wasm"
key_value_stores = [ "default" ]
[component.trigger]
route = "/key-value.json"
executor = { type = "wagi" }
[component.build]
command = "zig build key-value"

[[component]]
id = "json"
source = "zig-out/bin/json.wasm"
[component.trigger]
route = "/example.json"
executor = { type = "wagi" }
[component.build]
command = "zig build json"