spin_manifest_version = "1"
authors = ["Tobias Simetsreiter <tobias.simetsreiter@meliot.de>"]
description = ""
name = "spinapp"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "json"
source = "zig-out/bin/json.wasm"
key_value_stores = [ "default" ]
[component.trigger]
route = "/example.json"
executor = { type = "wagi" }
[component.build]
command = "zig build json"

[[component]]
id = "html"
source = "zig-out/bin/html.wasm"
[component.trigger]
route = "/..."
executor = { type = "wagi" }
[component.build]
command = "zig build html"
